<MDScreen>:
    md_bg_color: 0.96, 0.96, 0.96, 1

<MDRaisedButton>:
    md_bg_color: app.theme_cls.primary_color
    text_color: 1, 1, 1, 1
    size_hint_y: None
    height: "48dp"
    radius: [8, 8, 8, 8]

<MDTextField>:
    size_hint_y: None
    height: "48dp"
    mode: "fill"
    fill_color_normal: 1, 1, 1, 1
    line_color_normal: 0.8, 0.8, 0.8, 1
    line_color_focus: app.theme_cls.primary_color
